language: ruby
rvm:
  - 1.9.2
  - 1.9.3
env:
  - DB=postgresql
script: 
  - RAILS_ENV=test bundle exec rake --trace db:create db:migrate
  - bundle exec rake db:test:prepare
bundler_args: --binstubs=./bundler_stubs